extends: airbnb-base
env:
  browser: true
plugins:
  - import
rules:
  no-use-before-define: off
  prefer-rest-params: off
  comma-dangle: 
    - error
    - arrays: always
    - objects: always
    - imports: always
    - exports: always
    - functions: never